// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 17.1, macOS 14.1, tvOS 17.1, watchOS 10.1, visionOS 1.0, *)
extension SFSymbol {
    internal static var variantsAvailableSince5_1: [SFSymbol : (base: SFSymbol, type: String)] {
        [
            personCropSquareBadgeCameraFill: (base: .personCropSquareBadgeCamera, type: "fill"),
            personCropSquareBadgeVideoFill: (base: .personCropSquareBadgeVideo, type: "fill")
        ]
    }
}
