// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
extension SFSymbol {
    internal static let allRestrictions: [SFSymbol : Bool] = {
        var result = restrictionsAvailableSince1_0
        if #available(iOS 14.0, tvOS 14.0, watchOS 7.0, *) {
            result.merge(restrictionsAvailableSince2_0) { $0 || $1 }
        }
        if #available(iOS 14.2, tvOS 14.2, watchOS 7.1, *) {
            result.merge(restrictionsAvailableSince2_1) { $0 || $1 }
        }
        if #available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *) {
            result.merge(restrictionsAvailableSince2_2) { $0 || $1 }
        }
        if #available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *) {
            result.merge(restrictionsAvailableSince3_0) { $0 || $1 }
        }
        if #available(iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3, *) {
            result.merge(restrictionsAvailableSince3_2) { $0 || $1 }
        }
        if #available(iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5, *) {
            result.merge(restrictionsAvailableSince3_3) { $0 || $1 }
        }
        if #available(iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0, *) {
            result.merge(restrictionsAvailableSince4_0) { $0 || $1 }
        }
        if #available(iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1, *) {
            result.merge(restrictionsAvailableSince4_1) { $0 || $1 }
        }
        if #available(iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4, *) {
            result.merge(restrictionsAvailableSince4_2) { $0 || $1 }
        }
        if #available(iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0, *) {
            result.merge(restrictionsAvailableSince5_0) { $0 || $1 }
        }
        if #available(iOS 17.4, macOS 14.4, tvOS 17.4, watchOS 10.4, visionOS 1.1, *) {
            result.merge(restrictionsAvailableSince5_3) { $0 || $1 }
        }
        if #available(iOS 17.6, macOS 14.6, tvOS 17.6, watchOS 10.6, visionOS 1.3, *) {
            result.merge(restrictionsAvailableSince5_4) { $0 || $1 }
        }
        if #available(iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0, visionOS 2.0, *) {
            result.merge(restrictionsAvailableSince6_0) { $0 || $1 }
        }
        if #available(iOS 18.1, macOS 15.1, tvOS 18.1, watchOS 11.1, visionOS 2.1, *) {
            result.merge(restrictionsAvailableSince6_1) { $0 || $1 }
        }
        if #available(iOS 18.2, macOS 15.2, tvOS 18.2, watchOS 11.2, visionOS 2.2, *) {
            result.merge(restrictionsAvailableSince6_2) { $0 || $1 }
        }
        if #available(iOS 18.4, macOS 15.4, tvOS 18.4, watchOS 11.4, visionOS 2.4, *) {
            result.merge(restrictionsAvailableSince6_3) { $0 || $1 }
        }
        if #available(iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5, visionOS 2.5, *) {
            result.merge(restrictionsAvailableSince6_4) { $0 || $1 }
        }
        if #available(iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0, visionOS 26.0, *) {
            result.merge(restrictionsAvailableSince7_0) { $0 || $1 }
        }
        return result
    }()
}
