// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 18.2, macOS 15.2, tvOS 18.2, watchOS 11.2, visionOS 2.2, *)
extension SFSymbol {
    internal static var variantsAvailableSince6_2: [SFSymbol : (base: SFSymbol, type: String)] {
        [
            airpodsGen4ChargingcaseWirelessFill: (base: .airpodsGen4ChargingcaseWireless, type: "fill"),
            exclamationmarkTriangleTextPageFill: (base: .exclamationmarkTriangleTextPage, type: "fill"),
            infoTriangleFill: (base: .infoTriangle, type: "fill"),
            insetFilledRectangleAndPersonFilledCircle: (base: .insetFilledRectangleAndPersonFilled, type: "circle"),
            insetFilledRectangleAndPersonFilledCircleFill: (base: .insetFilledRectangleAndPersonFilledCircle, type: "fill"),
            receiptFill: (base: .receipt, type: "fill"),
            wandAndOutlineInverse: (base: .wandAndOutline, type: "inverse")
        ]
    }
}
