// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5, visionOS 2.5, *)
extension SFSymbol {
    internal static var keywordsAvailableSince6_4: [SFSymbol : Set<String>] {
        [
            beatsPowerbeatsPro2: ["audio", "sound", "speaker"],
            beatsPowerbeatsPro2Chargingcase: ["audio"],
            beatsPowerbeatsPro2ChargingcaseFill: ["audio"],
            beatsPowerbeatsPro2Left: ["audio", "sound", "speaker"],
            beatsPowerbeatsPro2Right: ["audio", "sound", "speaker"]
        ]
    }
}
