// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4, visionOS 1.0, *)
extension SFSymbol {
    internal static var restrictionsAvailableSince4_2: [SFSymbol : Bool] {
        [
            beatsPowerbeatsLeft: true,
            beatsPowerbeatsRight: true,
            beatsPowerbeats3Left: true,
            beatsPowerbeats3Right: true
        ]
    }
}
