// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 17.6, macOS 14.6, tvOS 17.6, watchOS 10.6, visionOS 1.3, *)
extension SFSymbol {
    internal static var variantsAvailableSince5_4: [SFSymbol : (base: SFSymbol, type: String)] {
        [
            beatsPillFill: (base: .beatsPill, type: "fill"),
            beatsSolobudsChargingcaseFill: (base: .beatsSolobudsChargingcase, type: "fill")
        ]
    }
}
