// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5, visionOS 1.0, *)
extension SFSymbol {
    internal static var keywordsAvailableSince3_3: [SFSymbol : Set<String>] {
        [
            cameraMacro: ["macro"],
            cameraMacroCircle: ["macro"],
            cameraMacroCircleFill: ["macro"],
            keyViewfinder: ["password", "security"],
            personBadgeKey: ["passkey", "password", "people", "privacyandsecurity", "user"],
            personBadgeKeyFill: ["passkey", "password", "people", "privacyandsecurity", "user"]
        ]
    }
}
