// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 18.4, macOS 15.4, tvOS 18.4, watchOS 11.4, visionOS 2.4, *)
extension SFSymbol {
    internal static var keywordsAvailableSince6_3: [SFSymbol : Set<String>] {
        [
            arrowBackwardToLineCompact: ["indent", "tab"],
            arrowForwardToLineCompact: ["indent", "tab"],
            macminiGen2: ["mac mini"],
            macminiGen2Fill: ["mac mini"],
            macminiGen3: ["mac mini"],
            macminiGen3Fill: ["mac mini"],
            memoriesSlash: ["arrow", "play"],
            nosignBadgeClock: ["block", "crossed out", "restricted", "slash"],
            personCheckmarkAndXmark: ["people", "user"],
            personFillCheckmarkAndXmark: ["people", "user"],
            photoBadgeShieldExclamationmark: ["environment", "image", "mountain", "photograph", "picture", "place", "sun"],
            photoBadgeShieldExclamationmarkFill: ["environment", "image", "mountain", "photograph", "picture", "place", "sun"],
            photoTrianglebadgeExclamationmark: ["environment", "image", "mountain", "photograph", "picture", "place", "sun"],
            photoTrianglebadgeExclamationmarkFill: ["environment", "image", "mountain", "photograph", "picture", "place", "sun"],
            spoonServing: ["drink", "food"],
            squareAndArrowUpBadgeCheckmark: ["export", "share", "sharrow", "upload"],
            squareAndArrowUpBadgeCheckmarkFill: ["export", "share", "sharrow", "upload"],
            squareshapeSplit2x2DottedInside: ["grid"]
        ]
    }
}
