// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 17.4, macOS 14.4, tvOS 17.4, watchOS 10.4, visionOS 1.1, *)
extension SFSymbol {
    internal static var restrictionsAvailableSince5_3: [SFSymbol : Bool] {
        [
            appleMeditate: true,
            appleMeditateSquareStack: true,
            appleMeditateSquareStackFill: true,
            ipadBadgeExclamationmark: true,
            ipadGen1BadgeExclamationmark: true,
            ipadGen1LandscapeBadgeExclamationmark: true,
            ipadGen2BadgeExclamationmark: true,
            ipadGen2LandscapeBadgeExclamationmark: true,
            ipadLandscapeBadgeExclamationmark: true,
            iphoneBadgeExclamationmark: true,
            iphoneGen1BadgeExclamationmark: true,
            iphoneGen2BadgeExclamationmark: true,
            iphoneGen3BadgeExclamationmark: true,
            translate: true
        ]
    }
}
