// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, visionOS 1.0, *)
extension SFSymbol {
    internal static var keywordsAvailableSince2_2: [SFSymbol : Set<String>] {
        [
            characterBubble: ["a"],
            characterBubbleFill: ["a"],
            characterCursorIbeam: ["a"],
            characterTextbox: ["a"]
        ]
    }
}
