// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 18.1, macOS 15.1, tvOS 18.1, watchOS 11.1, visionOS 2.1, *)
extension SFSymbol {
    internal static var categoriesAvailableSince6_1: [SFSymbol : Set<Category>] {
        [
            boltHouseFill: [.multicolor],
            cableConnectorVideo: [.devices],
            carTopRadiowaves2FrontLeftFrontFrontRight: [.automotive, .variable],
            carTopRadiowaves2FrontLeftFrontFrontRightFill: [.automotive, .variable],
            carTopRadiowaves2RearLeftRearRearRight: [.automotive, .variable],
            carTopRadiowaves2RearLeftRearRearRightFill: [.automotive, .variable],
            dotCarTopRadiowaves2RearLeftRearRearRight: [.automotive, .variable],
            dotCarTopRadiowaves2RearLeftRearRearRightFill: [.automotive, .variable],
            envelopeStack: [.communication],
            envelopeStackFill: [.communication],
            exclamationmarkMessage: [.communication],
            exclamationmarkMessageFill: [.communication, .multicolor],
            handThumbsdownSlash: [.human],
            handThumbsdownSlashFill: [.human],
            handThumbsupSlash: [.human],
            handThumbsupSlashFill: [.human],
            memoriesBadgeCheckmark: [.arrows, .multicolor],
            memoriesBadgeXmark: [.arrows, .multicolor],
            photoBadgeMagnifyingglass: [.cameraandphotos],
            photoBadgeMagnifyingglassFill: [.cameraandphotos],
            questionmarkMessage: [.communication],
            questionmarkMessageFill: [.communication, .multicolor],
            squareAndArrowDownBadgeCheckmark: [.multicolor],
            squareAndArrowDownBadgeCheckmarkFill: [.multicolor],
            squareAndArrowDownBadgeXmark: [.multicolor],
            squareAndArrowDownBadgeXmarkFill: [.multicolor],
            waveformBadgeCheckmark: [.communication, .multicolor, .variable],
            waveformBadgeXmark: [.communication, .multicolor, .variable],
            waveformPathEcgMagnifyingglass: [.objectsandtools],
            waveformPathEcgTextClipboard: [.health, .objectsandtools],
            waveformPathEcgTextClipboardFill: [.health, .objectsandtools]
        ]
    }
}
