// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, visionOS 1.0, *)
extension SFSymbol {
    internal static var keywordsAvailableSince3_1: [SFSymbol : Set<String>] {
        [
            boltRingClosed: ["energy", "power"]
        ]
    }
}
