// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, visionOS 1.0, *)
extension SFSymbol {
    internal static var categoriesAvailableSince3_1: [SFSymbol : Set<Category>] {
        [
            platterFilledBottomAndArrowDownIphone: [.devices],
            platterFilledBottomIphone: [.devices],
            platterFilledTopAndArrowUpIphone: [.devices],
            platterFilledTopIphone: [.devices],
            square3Layers3dDownBackward: [.cameraandphotos, .variable],
            square3Layers3dDownForward: [.cameraandphotos, .variable],
            square3Layers3dDownLeft: [.cameraandphotos, .variable],
            square3Layers3dDownRight: [.cameraandphotos, .variable],
            textJustifyLeading: [.textformatting],
            textJustifyLeft: [.textformatting],
            textJustifyRight: [.textformatting],
            textJustifyTrailing: [.textformatting]
        ]
    }
}
