// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 18.1, macOS 15.1, tvOS 18.1, watchOS 11.1, visionOS 2.1, *)
extension SFSymbol {
    internal static var restrictionsAvailableSince6_1: [SFSymbol : Bool] {
        [
            exclamationmarkMessage: true,
            exclamationmarkMessageFill: true,
            questionmarkMessage: true,
            questionmarkMessageFill: true
        ]
    }
}
