// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 13.1, macOS 11.0, tvOS 13.0, watchOS 6.1, visionOS 1.0, *)
extension SFSymbol {
    internal static var categoriesAvailableSince1_1: [SFSymbol : Set<Category>] {
        [
            arrowUturnLeftCircleBadgeEllipsis: [.arrows, .multicolor, .variable],
            aspectratio: [.editing],
            aspectratioFill: [.editing],
            car: [.automotive, .devices, .maps, .multicolor, .transportation],
            flashlightOffFill: [.objectsandtools],
            flashlightOnFill: [.objectsandtools],
            mappinCircle: [.maps, .multicolor, .objectsandtools, .variable],
            mappinCircleFill: [.maps, .multicolor, .objectsandtools],
            paperclipCircle: [.objectsandtools, .variable],
            paperclipCircleFill: [.multicolor, .objectsandtools],
            pinCircle: [.multicolor, .objectsandtools, .variable],
            pinCircleFill: [.multicolor, .objectsandtools],
            scissorsBadgeEllipsis: [.editing, .multicolor, .objectsandtools],
            studentdesk: [.objectsandtools]
        ]
    }
}
