// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 18.2, macOS 15.2, tvOS 18.2, watchOS 11.2, visionOS 2.2, *)
extension SFSymbol {
    internal static var categoriesAvailableSince6_2: [SFSymbol : Set<Category>] {
        [
            airpodsGen4: [.devices],
            airpodsGen4ChargingcaseWireless: [.devices],
            airpodsGen4ChargingcaseWirelessFill: [.devices],
            airpodsGen4Left: [.devices],
            airpodsGen4Right: [.devices],
            appleWritingTools: [.multicolor],
            figureSeatedSideLeftAirDistributionUpperAndMiddleAndLower: [.automotive, .human],
            figureSeatedSideRightAirDistributionUpperAndMiddleAndLower: [.automotive, .human],
            headphonesDots: [.devices, .objectsandtools, .variable],
            infoTriangleFill: [.multicolor],
            insetFilledRectangleAndPersonFilledCircle: [.human, .variable],
            insetFilledRectangleAndPersonFilledCircleFill: [.human, .multicolor],
            receipt: [.objectsandtools],
            receiptFill: [.objectsandtools],
            wandAndOutline: [.editing, .objectsandtools],
            wandAndOutlineInverse: [.editing, .objectsandtools]
        ]
    }
}
