// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, visionOS 1.0, *)
extension SFSymbol {
    internal static var variantsAvailableSince2_1: [SFSymbol : (base: SFSymbol, type: String)] {
        [
            brazilianrealsignCircleFill: (base: .brazilianrealsignCircle, type: "fill"),
            brazilianrealsignSquareFill: (base: .brazilianrealsignSquare, type: "fill"),
            cartCircle: (base: .cart, type: "circle"),
            cartCircleFill: (base: .cartCircle, type: "fill"),
            characterBookClosedFill: (base: .characterBookClosed, type: "fill"),
            infinityCircle: (base: .infinity, type: "circle"),
            infinityCircleFill: (base: .infinityCircle, type: "fill"),
            playTvFill: (base: .playTv, type: "fill"),
            rectangleBadgePersonCrop: (base: .rectangle, type: "badge"),
            rectangleFillBadgePersonCrop: (base: .rectangleFill, type: "badge"),
            repeat1Circle: (base: .repeat1, type: "circle"),
            repeat1CircleFill: (base: .repeat1Circle, type: "fill"),
            repeatCircle: (base: .`repeat`, type: "circle"),
            repeatCircleFill: (base: .repeatCircle, type: "fill"),
            shuffleCircle: (base: .shuffle, type: "circle"),
            shuffleCircleFill: (base: .shuffleCircle, type: "fill")
        ]
    }
}
