// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 18.2, macOS 15.2, tvOS 18.2, watchOS 11.2, visionOS 2.2, *)
extension SFSymbol {
    internal static var restrictionsAvailableSince6_2: [SFSymbol : Bool] {
        [
            airpodsGen4: true,
            airpodsGen4ChargingcaseWireless: true,
            airpodsGen4ChargingcaseWirelessFill: true,
            airpodsGen4Left: true,
            airpodsGen4Right: true,
            appleWritingTools: true
        ]
    }
}
