// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 13.1, macOS 11.0, tvOS 13.0, watchOS 6.1, visionOS 1.0, *)
extension SFSymbol {
    internal static var keywordsAvailableSince1_1: [SFSymbol : Set<String>] {
        [
            arrowUturnLeftCircleBadgeEllipsis: ["action", "dot.3", "extra", "more", "overflow", "…"],
            paperclipCircle: ["attach", "attachments"],
            paperclipCircleFill: ["attach", "attachments"],
            pinCircle: ["pin"],
            pinCircleFill: ["pin"],
            scissorsBadgeEllipsis: ["action", "dot.3", "extra", "more", "overflow", "…"]
        ]
    }
}
