// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5, visionOS 2.5, *)
extension SFSymbol {
    internal static var restrictionsAvailableSince6_4: [SFSymbol : Bool] {
        [
            appleIntelligenceBadgeXmark: true,
            beatsPowerbeatsPro2: true,
            beatsPowerbeatsPro2Chargingcase: true,
            beatsPowerbeatsPro2ChargingcaseFill: true,
            beatsPowerbeatsPro2Left: true,
            beatsPowerbeatsPro2Right: true
        ]
    }
}
