// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, visionOS 1.0, *)
extension SFSymbol {
    internal static var restrictionsAvailableSince2_1: [SFSymbol : Bool] {
        [
            exclamationmarkApplewatch: true,
            ipadBadgePlay: true,
            ipadHomebuttonBadgePlay: true,
            ipadHomebuttonLandscapeBadgePlay: true,
            ipadLandscapeBadgePlay: true,
            iphoneBadgePlay: true,
            iphoneHomebuttonBadgePlay: true,
            iphoneHomebuttonLandscape: true,
            iphoneLandscape: true,
            ipodtouchLandscape: true,
            lockApplewatch: true
        ]
    }
}
