// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 17.6, macOS 14.6, tvOS 17.6, watchOS 10.6, visionOS 1.3, *)
extension SFSymbol {
    internal static var restrictionsAvailableSince5_4: [SFSymbol : Bool] {
        [
            beatsPill: true,
            beatsPillFill: true,
            beatsSolobuds: true,
            beatsSolobudsChargingcase: true,
            beatsSolobudsChargingcaseFill: true,
            beatsSolobudsLeft: true,
            beatsSolobudsRight: true
        ]
    }
}
