// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 18.4, macOS 15.4, tvOS 18.4, watchOS 11.4, visionOS 2.4, *)
extension SFSymbol {
    internal static var restrictionsAvailableSince6_3: [SFSymbol : Bool] {
        [
            macminiGen2: true,
            macminiGen2Fill: true,
            macminiGen3: true,
            macminiGen3Fill: true
        ]
    }
}
