// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4, visionOS 1.0, *)
extension SFSymbol {
    internal static var categoriesAvailableSince4_2: [SFSymbol : Set<Category>] {
        [
            axle2: [.automotive],
            axle2FrontAndRearEngaged: [.automotive],
            axle2FrontEngaged: [.automotive],
            axle2RearEngaged: [.automotive],
            beatsPowerbeatsLeft: [.devices],
            beatsPowerbeatsRight: [.devices],
            beatsPowerbeats3Left: [.devices],
            beatsPowerbeats3Right: [.devices]
        ]
    }
}
