// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 18.2, macOS 15.2, tvOS 18.2, watchOS 11.2, visionOS 2.2, *)
extension SFSymbol {
    internal static var keywordsAvailableSince6_2: [SFSymbol : Set<String>] {
        [
            airpodsGen4: ["audio"],
            airpodsGen4ChargingcaseWireless: ["audio"],
            airpodsGen4ChargingcaseWirelessFill: ["audio"],
            airpodsGen4Left: ["audio"],
            airpodsGen4Right: ["audio"],
            figureSeatedSideLeftAirDistributionUpperAndMiddleAndLower: ["arrow", "human", "person"],
            figureSeatedSideRightAirDistributionUpperAndMiddleAndLower: ["arrow", "human", "person"],
            headphonesDots: ["audio", "sound", "speaker"],
            insetFilledRectangleAndPersonFilledCircle: ["people", "screen sharing"],
            insetFilledRectangleAndPersonFilledCircleFill: ["people", "screen sharing"]
        ]
    }
}
