// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5, visionOS 2.5, *)
extension SFSymbol {
    internal static var categoriesAvailableSince6_4: [SFSymbol : Set<Category>] {
        [
            appleIntelligenceBadgeXmark: [.multicolor],
            beatsPowerbeatsPro2: [.devices],
            beatsPowerbeatsPro2Chargingcase: [.devices],
            beatsPowerbeatsPro2ChargingcaseFill: [.devices],
            beatsPowerbeatsPro2Left: [.devices],
            beatsPowerbeatsPro2Right: [.devices]
        ]
    }
}
