// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0, visionOS 1.0, *)
extension SFSymbol {
    internal static var restrictionsAvailableSince4_0: [SFSymbol : Bool] {
        [
            appleLogo: true,
            arrowDownMessage: true,
            arrowDownMessageFill: true,
            checkmarkMessage: true,
            checkmarkMessageFill: true,
            deskview: true,
            deskviewFill: true,
            ellipsisMessage: true,
            ellipsisMessageFill: true,
            laptopcomputerAndIpad: true,
            macstudio: true,
            macstudioFill: true,
            messageBadge: true,
            messageBadgeCircle: true,
            messageBadgeCircleFill: true,
            messageBadgeFill: true,
            messageBadgeFilledFill: true,
            playstationLogo: true,
            sharedWithYou: true,
            sharedWithYouSlash: true,
            shazamLogo: true,
            shazamLogoFill: true,
            xboxLogo: true
        ]
    }
}
