// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 18.1, macOS 15.1, tvOS 18.1, watchOS 11.1, visionOS 2.1, *)
extension SFSymbol {
    internal static var keywordsAvailableSince6_1: [SFSymbol : Set<String>] {
        [
            boltHouse: ["home", "house"],
            boltHouseFill: ["home", "house"],
            envelopeStack: ["address", "letter", "mail"],
            envelopeStackFill: ["address", "letter", "mail"],
            photoBadgeMagnifyingglass: ["environment", "image", "mountain", "photograph", "picture", "place", "sun"],
            photoBadgeMagnifyingglassFill: ["environment", "image", "mountain", "photograph", "picture", "place", "sun"],
            squareAndArrowDownBadgeCheckmark: ["download", "import", "save"],
            squareAndArrowDownBadgeCheckmarkFill: ["download", "import", "save"],
            squareAndArrowDownBadgeXmark: ["download", "import", "save"],
            squareAndArrowDownBadgeXmarkFill: ["download", "import", "save"],
            waveformPathEcgTextClipboard: ["notes"],
            waveformPathEcgTextClipboardFill: ["notes"]
        ]
    }
}
