// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 18.1, macOS 15.1, tvOS 18.1, watchOS 11.1, visionOS 2.1, *)
extension SFSymbol {
    internal static var variantsAvailableSince6_1: [SFSymbol : (base: SFSymbol, type: String)] {
        [
            boltHouseFill: (base: .boltHouse, type: "fill"),
            carTopRadiowaves2FrontLeftFrontFrontRightFill: (base: .carTopRadiowaves2FrontLeftFrontFrontRight, type: "fill"),
            carTopRadiowaves2RearLeftRearRearRightFill: (base: .carTopRadiowaves2RearLeftRearRearRight, type: "fill"),
            dotCarTopRadiowaves2RearLeftRearRearRightFill: (base: .dotCarTopRadiowaves2RearLeftRearRearRight, type: "fill"),
            envelopeStack: (base: .envelope, type: "stack"),
            envelopeStackFill: (base: .envelopeStack, type: "fill"),
            exclamationmarkMessageFill: (base: .exclamationmarkMessage, type: "fill"),
            handThumbsdownSlash: (base: .handThumbsdown, type: "slash"),
            handThumbsdownSlashFill: (base: .handThumbsdownSlash, type: "fill"),
            handThumbsupSlash: (base: .handThumbsup, type: "slash"),
            handThumbsupSlashFill: (base: .handThumbsupSlash, type: "fill"),
            memoriesBadgeCheckmark: (base: .memories, type: "badge"),
            memoriesBadgeXmark: (base: .memories, type: "badge"),
            photoBadgeMagnifyingglassFill: (base: .photoBadgeMagnifyingglass, type: "fill"),
            questionmarkMessageFill: (base: .questionmarkMessage, type: "fill"),
            rectangleGrid3x1Fill: (base: .rectangleGrid3x1, type: "fill"),
            squareAndArrowDownBadgeCheckmark: (base: .squareAndArrowDown, type: "badge"),
            squareAndArrowDownBadgeCheckmarkFill: (base: .squareAndArrowDownBadgeCheckmark, type: "fill"),
            squareAndArrowDownBadgeXmark: (base: .squareAndArrowDown, type: "badge"),
            squareAndArrowDownBadgeXmarkFill: (base: .squareAndArrowDownBadgeXmark, type: "fill"),
            waveformBadgeCheckmark: (base: .waveform, type: "badge"),
            waveformBadgeXmark: (base: .waveform, type: "badge"),
            waveformPathEcgTextClipboardFill: (base: .waveformPathEcgTextClipboard, type: "fill"),
            waveformPathEcgTextPageFill: (base: .waveformPathEcgTextPage, type: "fill")
        ]
    }
}
