// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3, visionOS 1.0, *)
extension SFSymbol {
    internal static var categoriesAvailableSince3_2: [SFSymbol : Set<Category>] {
        [
            airpodGen3Left: [.devices],
            airpodGen3Right: [.devices],
            airpodsGen3: [.devices],
            airpodsGen3ChargingcaseWireless: [.devices],
            airpodsGen3ChargingcaseWirelessFill: [.devices],
            square3Layers3dDownLeftSlash: [.cameraandphotos],
            square3Layers3dDownRightSlash: [.cameraandphotos]
        ]
    }
}
