// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 17.4, macOS 14.4, tvOS 17.4, watchOS 10.4, visionOS 1.1, *)
extension SFSymbol {
    internal static var categoriesAvailableSince5_3: [SFSymbol : Set<Category>] {
        [
            appleMeditate: [.health, .nature],
            appleMeditateSquareStack: [.health, .nature],
            appleMeditateSquareStackFill: [.health, .nature],
            appleTerminalCircle: [.variable],
            appleTerminalCircleFill: [.multicolor],
            arrowDownAppDashedTrianglebadgeExclamationmark: [.multicolor],
            audioJackMono: [.devices],
            audioJackStereo: [.devices],
            ipadBadgeExclamationmark: [.devices, .multicolor],
            ipadGen1BadgeExclamationmark: [.devices, .multicolor],
            ipadGen1LandscapeBadgeExclamationmark: [.devices, .multicolor],
            ipadGen2BadgeExclamationmark: [.devices, .multicolor],
            ipadGen2LandscapeBadgeExclamationmark: [.devices, .multicolor],
            ipadLandscapeBadgeExclamationmark: [.devices, .multicolor],
            iphoneBadgeExclamationmark: [.devices, .multicolor],
            iphoneGen1BadgeExclamationmark: [.devices, .multicolor],
            iphoneGen2BadgeExclamationmark: [.devices, .multicolor],
            iphoneGen3BadgeExclamationmark: [.devices, .multicolor],
            medalStar: [.objectsandtools],
            medalStarFill: [.objectsandtools],
            translate: [.communication]
        ]
    }
}
