// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3, visionOS 1.0, *)
extension SFSymbol {
    internal static var variantsAvailableSince3_2: [SFSymbol : (base: SFSymbol, type: String)] {
        [
            airpodsGen3ChargingcaseWirelessFill: (base: .airpodsGen3ChargingcaseWireless, type: "fill"),
            beatsFitProChargingcaseFill: (base: .beatsFitProChargingcase, type: "fill"),
            square3Layers3dDownLeftSlash: (base: .square3Layers3dDownLeft, type: "slash"),
            square3Layers3dDownRightSlash: (base: .square3Layers3dDownRight, type: "slash"),
            square3Stack3dSlash: (base: .square3Stack3d, type: "slash")
        ]
    }
}
