// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, visionOS 1.0, *)
extension SFSymbol {
    internal static var keywordsAvailableSince2_1: [SFSymbol : Set<String>] {
        [
            aqiHigh: ["!", "warning", "weather"],
            aqiLow: ["weather"],
            aqiMedium: ["weather"],
            brazilianrealsignCircle: ["currencies", "currency"],
            brazilianrealsignCircleFill: ["currencies", "currency"],
            brazilianrealsignSquare: ["currencies", "currency"],
            brazilianrealsignSquareFill: ["currencies", "currency"],
            character: ["a"],
            characterBookClosed: ["dictionary"],
            characterBookClosedFill: ["dictionary"],
            exclamationmarkApplewatch: ["warning"],
            lockApplewatch: ["padlock", "password", "security"],
            photoTv: ["environment", "image", "mountain", "photograph", "picture", "place", "sun"],
            rectangleBadgePersonCrop: ["people"],
            rectangleFillBadgePersonCrop: ["people"],
            repeat1Circle: ["arrow", "arrow.trianglehead", "trianglehead"],
            repeat1CircleFill: ["arrow", "arrow.trianglehead", "trianglehead"],
            repeatCircle: ["arrow", "arrow.trianglehead", "trianglehead"],
            repeatCircleFill: ["arrow", "arrow.trianglehead", "trianglehead"],
            shuffleCircle: ["arrow", "arrow.trianglehead", "trianglehead"],
            shuffleCircleFill: ["arrow", "arrow.trianglehead", "trianglehead"]
        ]
    }
}
