// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 6.3 Symbols
@available(iOS 18.4, macOS 15.4, tvOS 18.4, watchOS 11.4, visionOS 2.4, *)
public extension SFSymbol {
    /// 􁂋
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// Categories:
    /// - Arrows
    /// - Keyboard
    static var arrowBackwardToLineCompact: SFSymbol { .init(rawValue: "arrow.backward.to.line.compact") }

    /// 􁂏
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// Categories:
    /// - Arrows
    /// - Keyboard
    static var arrowForwardToLineCompact: SFSymbol { .init(rawValue: "arrow.forward.to.line.compact") }

    /// 􂹼
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var carSideArrowLeftAndRight: SFSymbol { .init(rawValue: "car.side.arrow.left.and.right") }

    /// 􂹽
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var carSideArrowLeftAndRightFill: SFSymbol { .init(rawValue: "car.side.arrow.left.and.right.fill") }

    /// 􂼛
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Automotive
    static var carSideHillDownAndGaugeOpenWithLinesNeedle25percentAndArrowtriangle: SFSymbol { .init(rawValue: "car.side.hill.down.and.gauge.open.with.lines.needle.25percent.and.arrowtriangle") }

    /// 􂼜
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Automotive
    static var carSideHillDownAndGaugeOpenWithLinesNeedle25percentAndArrowtriangleFill: SFSymbol { .init(rawValue: "car.side.hill.down.and.gauge.open.with.lines.needle.25percent.and.arrowtriangle.fill") }

    /// 􂻳
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var carSideRearAndCollisionAndCarSideFrontAndArrowForward: SFSymbol { .init(rawValue: "car.side.rear.and.collision.and.car.side.front.and.arrow.forward") }

    /// 􂼚
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var carSideRearAndCollisionAndCarSideFrontAndSteeringwheel: SFSymbol { .init(rawValue: "car.side.rear.and.collision.and.car.side.front.and.steeringwheel") }

    /// 􂺯
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var carTopLaneDashedDepartureLeftSlash: SFSymbol { .init(rawValue: "car.top.lane.dashed.departure.left.slash") }

    /// 􂺱
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var carTopLaneDashedDepartureLeftSlashFill: SFSymbol { .init(rawValue: "car.top.lane.dashed.departure.left.slash.fill") }

    /// 􂺳
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var carTopLaneDashedDepartureRightSlash: SFSymbol { .init(rawValue: "car.top.lane.dashed.departure.right.slash") }

    /// 􂺵
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var carTopLaneDashedDepartureRightSlashFill: SFSymbol { .init(rawValue: "car.top.lane.dashed.departure.right.slash.fill") }

    /// 􂺹
    /// 19 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Bengali
    /// - Chinese
    /// - Gujarati
    /// - Hebrew
    /// - Hindi
    /// - Japanese
    /// - Kannada
    /// - Korean
    /// - Malayalam
    /// - Manipuri
    /// - Maranthi
    /// - Oriya
    /// - Punjabi
    /// - Santali
    /// - Sinhala
    /// - Tamil
    /// - Thai
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Text Formatting
    static var characterTextboxBadgeSparkles: SymbolWith18Localizations<Ar, Bn, Gu, He, Hi, Ja, Kn, Ko, Ml, Mni, Mr, Or, Pa, Sat, Si, Ta, Th, Zh> { .init(rawValue: "character.textbox.badge.sparkles") }

    /// 􂺀
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var convertibleSideArrowLeftAndRight: SFSymbol { .init(rawValue: "convertible.side.arrow.left.and.right") }

    /// 􂺁
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var convertibleSideArrowLeftAndRightFill: SFSymbol { .init(rawValue: "convertible.side.arrow.left.and.right.fill") }

    /// 􂼧
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Automotive
    static var convertibleSideHillDownAndGaugeOpenWithLinesNeedle25percentAndArrowtriangle: SFSymbol { .init(rawValue: "convertible.side.hill.down.and.gauge.open.with.lines.needle.25percent.and.arrowtriangle") }

    /// 􂼨
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Automotive
    static var convertibleSideHillDownAndGaugeOpenWithLinesNeedle25percentAndArrowtriangleFill: SFSymbol { .init(rawValue: "convertible.side.hill.down.and.gauge.open.with.lines.needle.25percent.and.arrowtriangle.fill") }

    /// 􀫌
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    @available(iOS, introduced: 18.4, deprecated: 26.0, renamed: "pointerArrow")
    @available(macOS, introduced: 15.4, deprecated: 26.0, renamed: "pointerArrow")
    @available(tvOS, introduced: 18.4, deprecated: 26.0, renamed: "pointerArrow")
    @available(watchOS, introduced: 11.4, deprecated: 26.0, renamed: "pointerArrow")
    @available(visionOS, introduced: 2.4, deprecated: 26.0, renamed: "pointerArrow")
    static var cursorarrowResizeNorthEastSouthEast: SFSymbol { .init(rawValue: "cursorarrow.resize.north.east.south.east") }

    /// 􂼙
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// Categories:
    /// - Automotive
    static var electronicTollCollection: SFSymbol { .init(rawValue: "electronic.toll.collection") }

    /// 􂺟
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var electronicTollCollectionRectangle: SFSymbol { .init(rawValue: "electronic.toll.collection.rectangle") }

    /// 􂺦
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Automotive
    /// - Multicolor
    static var electronicTollCollectionRectangleFill: SFSymbol { .init(rawValue: "electronic.toll.collection.rectangle.fill") }

    /// 􂺠
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var electronicTollCollectionRectangleSlash: SFSymbol { .init(rawValue: "electronic.toll.collection.rectangle.slash") }

    /// 􂺧
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var electronicTollCollectionRectangleSlashFill: SFSymbol { .init(rawValue: "electronic.toll.collection.rectangle.slash.fill") }

    /// 􂺢
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Automotive
    /// - Multicolor
    static var electronicTollCollectionRectangleTrianglebadgeExclamationmark: SFSymbol { .init(rawValue: "electronic.toll.collection.rectangle.trianglebadge.exclamationmark") }

    /// 􂺩
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Automotive
    /// - Multicolor
    static var electronicTollCollectionRectangleTrianglebadgeExclamationmarkFill: SFSymbol { .init(rawValue: "electronic.toll.collection.rectangle.trianglebadge.exclamationmark.fill") }

    /// 􂼵
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Automotive
    static var engineEmissionAndDrop2WaterWaveBelow: SFSymbol { .init(rawValue: "engine.emission.and.drop.2.water.wave.below") }

    /// 􂻴
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static var envelopeAndArrow3Down: SFSymbol { .init(rawValue: "envelope.and.arrow.3.down") }

    /// 􂻵
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static var envelopeAndArrow3DownFill: SFSymbol { .init(rawValue: "envelope.and.arrow.3.down.fill") }

    /// 􂼊
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// Categories:
    /// - Automotive
    /// - Objects & Tools
    static var flagPatternCheckeredLc: SFSymbol { .init(rawValue: "flag.pattern.checkered.lc") }

    /// 􂼋
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// Categories:
    /// - Automotive
    static var fuelFilterWater: SFSymbol { .init(rawValue: "fuel.filter.water") }

    /// 􂼅
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// Categories:
    /// - Automotive
    static var hydrogen: SFSymbol { .init(rawValue: "hydrogen") }

    /// 􂼆
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    /// - Variable
    static var hydrogenCircle: SFSymbol { .init(rawValue: "hydrogen.circle") }

    /// 􂼇
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Automotive
    /// - Multicolor
    static var hydrogenCircleFill: SFSymbol { .init(rawValue: "hydrogen.circle.fill") }

    /// 􂼈
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var hydrogenSquare: SFSymbol { .init(rawValue: "hydrogen.square") }

    /// 􂼉
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Automotive
    /// - Multicolor
    static var hydrogenSquareFill: SFSymbol { .init(rawValue: "hydrogen.square.fill") }

    /// 􂹚
    /// 2 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    static var infoCircleTextPage: SymbolWith1Localization<Rtl> { .init(rawValue: "info.circle.text.page") }

    /// 􂹛
    /// 2 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    static var infoCircleTextPageFill: SymbolWith1Localization<Rtl> { .init(rawValue: "info.circle.text.page.fill") }

    /// 􂻶
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var keyCarSide: SFSymbol { .init(rawValue: "key.car.side") }

    /// 􂻷
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Automotive
    /// - Multicolor
    static var keyCarSideFill: SFSymbol { .init(rawValue: "key.car.side.fill") }

    /// 􂻺
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var keyConvertibleSide: SFSymbol { .init(rawValue: "key.convertible.side") }

    /// 􂻻
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Automotive
    /// - Multicolor
    static var keyConvertibleSideFill: SFSymbol { .init(rawValue: "key.convertible.side.fill") }

    /// 􂻸
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var keySuvSide: SFSymbol { .init(rawValue: "key.suv.side") }

    /// 􂻹
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Automotive
    /// - Multicolor
    static var keySuvSideFill: SFSymbol { .init(rawValue: "key.suv.side.fill") }

    /// 􂻼
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var keyTruckPickupSide: SFSymbol { .init(rawValue: "key.truck.pickup.side") }

    /// 􂻽
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Automotive
    /// - Multicolor
    static var keyTruckPickupSideFill: SFSymbol { .init(rawValue: "key.truck.pickup.side.fill") }

    /// 􂽱
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static var longTextPageAndPencil: SFSymbol { .init(rawValue: "long.text.page.and.pencil") }

    /// 􂽴
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static var longTextPageAndPencilFill: SFSymbol { .init(rawValue: "long.text.page.and.pencil.fill") }

    /// 􂶷
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// Categories:
    /// - Devices
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Mac mini.
    static var macminiGen2: SFSymbol { .init(rawValue: "macmini.gen2") }

    /// 􂶸
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// Categories:
    /// - Devices
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Mac mini.
    static var macminiGen2Fill: SFSymbol { .init(rawValue: "macmini.gen2.fill") }

    /// 􂶹
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// Categories:
    /// - Devices
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Mac mini.
    static var macminiGen3: SFSymbol { .init(rawValue: "macmini.gen3") }

    /// 􂶺
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// Categories:
    /// - Devices
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Mac mini.
    static var macminiGen3Fill: SFSymbol { .init(rawValue: "macmini.gen3.fill") }

    /// 􂺂
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Arrows
    static var memoriesSlash: SFSymbol { .init(rawValue: "memories.slash") }

    /// 􂹸
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    /// - Objects & Tools
    static var minusPlusBatteryblockStackArrowtriangleLeft: SFSymbol { .init(rawValue: "minus.plus.batteryblock.stack.arrowtriangle.left") }

    /// 􂹺
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Automotive
    /// - Multicolor
    /// - Objects & Tools
    static var minusPlusBatteryblockStackArrowtriangleLeftFill: SFSymbol { .init(rawValue: "minus.plus.batteryblock.stack.arrowtriangle.left.fill") }

    /// 􂹴
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    /// - Objects & Tools
    static var minusPlusBatteryblockStackArrowtriangleRight: SFSymbol { .init(rawValue: "minus.plus.batteryblock.stack.arrowtriangle.right") }

    /// 􂼕
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    /// - Objects & Tools
    static var minusPlusBatteryblockStackArrowtriangleRightAndArrowtriangleLeft: SFSymbol { .init(rawValue: "minus.plus.batteryblock.stack.arrowtriangle.right.and.arrowtriangle.left") }

    /// 􂼖
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Automotive
    /// - Multicolor
    /// - Objects & Tools
    static var minusPlusBatteryblockStackArrowtriangleRightAndArrowtriangleLeftFill: SFSymbol { .init(rawValue: "minus.plus.batteryblock.stack.arrowtriangle.right.and.arrowtriangle.left.fill") }

    /// 􂹶
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Automotive
    /// - Multicolor
    /// - Objects & Tools
    static var minusPlusBatteryblockStackArrowtriangleRightFill: SFSymbol { .init(rawValue: "minus.plus.batteryblock.stack.arrowtriangle.right.fill") }

    /// 􂼫
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Multicolor
    /// - Privacy & Security
    static var nosignBadgeClock: SFSymbol { .init(rawValue: "nosign.badge.clock") }

    /// 􂻫
    /// 2 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Human
    static var personCheckmarkAndXmark: SymbolWith1Localization<Rtl> { .init(rawValue: "person.checkmark.and.xmark") }

    /// 􂻬
    /// 2 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Human
    static var personFillCheckmarkAndXmark: SymbolWith1Localization<Rtl> { .init(rawValue: "person.fill.checkmark.and.xmark") }

    /// 􂼭
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Camera & Photos
    /// - Multicolor
    static var photoBadgeShieldExclamationmark: SFSymbol { .init(rawValue: "photo.badge.shield.exclamationmark") }

    /// 􂼷
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Camera & Photos
    /// - Multicolor
    static var photoBadgeShieldExclamationmarkFill: SFSymbol { .init(rawValue: "photo.badge.shield.exclamationmark.fill") }

    /// 􂼯
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Camera & Photos
    /// - Multicolor
    static var photoTrianglebadgeExclamationmark: SFSymbol { .init(rawValue: "photo.trianglebadge.exclamationmark") }

    /// 􂼸
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Camera & Photos
    /// - Multicolor
    static var photoTrianglebadgeExclamationmarkFill: SFSymbol { .init(rawValue: "photo.trianglebadge.exclamationmark.fill") }

    /// 􂹯
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// Categories:
    /// - Math
    static var pi: SFSymbol { .init(rawValue: "pi") }

    /// 􂹰
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Math
    /// - Variable
    static var piCircle: SFSymbol { .init(rawValue: "pi.circle") }

    /// 􂹱
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Math
    /// - Multicolor
    static var piCircleFill: SFSymbol { .init(rawValue: "pi.circle.fill") }

    /// 􂹲
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Math
    static var piSquare: SFSymbol { .init(rawValue: "pi.square") }

    /// 􂹳
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Math
    /// - Multicolor
    static var piSquareFill: SFSymbol { .init(rawValue: "pi.square.fill") }

    /// 􂻥
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static var plusMinusCapsule: SFSymbol { .init(rawValue: "plus.minus.capsule") }

    /// 􂻦
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    /// - Multicolor (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Multicolor
    static var plusMinusCapsuleFill: SFSymbol { .init(rawValue: "plus.minus.capsule.fill") }

    /// 􂻛
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    @available(iOS, introduced: 18.4, deprecated: 26.0, renamed: "repeatBadgeXmark")
    @available(macOS, introduced: 15.4, deprecated: 26.0, renamed: "repeatBadgeXmark")
    @available(tvOS, introduced: 18.4, deprecated: 26.0, renamed: "repeatBadgeXmark")
    @available(watchOS, introduced: 11.4, deprecated: 26.0, renamed: "repeatBadgeXmark")
    @available(visionOS, introduced: 2.4, deprecated: 26.0, renamed: "repeatBadgeXmark")
    static var repeatBadgeXmarkCircleFill: SFSymbol { .init(rawValue: "repeat.badge.xmark.circle.fill") }

    /// 􂼀
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Automotive
    static var roadLaneArrowtriangle2Outward: SFSymbol { .init(rawValue: "road.lane.arrowtriangle.2.outward") }

    /// 􂼳
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Home
    /// - Objects & Tools
    static var roboticVacuumAndArrowtriangleUp: SFSymbol { .init(rawValue: "robotic.vacuum.and.arrowtriangle.up") }

    /// 􂼴
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Home
    /// - Objects & Tools
    static var roboticVacuumAndArrowtriangleUpFill: SFSymbol { .init(rawValue: "robotic.vacuum.and.arrowtriangle.up.fill") }

    /// 􂼱
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    ///
    /// Categories:
    /// - Home
    /// - Objects & Tools
    /// - Variable
    static var roboticVacuumAndEllipsis: SFSymbol { .init(rawValue: "robotic.vacuum.and.ellipsis") }

    /// 􂼲
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    ///
    /// Categories:
    /// - Home
    /// - Objects & Tools
    /// - Variable
    static var roboticVacuumAndEllipsisFill: SFSymbol { .init(rawValue: "robotic.vacuum.and.ellipsis.fill") }

    /// 􂻝
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// Categories:
    /// - Objects & Tools
    static var spoonServing: SFSymbol { .init(rawValue: "spoon.serving") }

    /// 􂼽
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Multicolor
    static var squareAndArrowUpBadgeCheckmark: SFSymbol { .init(rawValue: "square.and.arrow.up.badge.checkmark") }

    /// 􂼾
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// Categories:
    /// - Multicolor
    static var squareAndArrowUpBadgeCheckmarkFill: SFSymbol { .init(rawValue: "square.and.arrow.up.badge.checkmark.fill") }

    /// 􀮌
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static var squareshapeSplit2x2DottedInside: SFSymbol { .init(rawValue: "squareshape.split.2x2.dotted.inside") }

    /// 􁓓
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static var squareshapeSplit2x2DottedInsideAndOutside: SFSymbol { .init(rawValue: "squareshape.split.2x2.dotted.inside.and.outside") }

    /// 􂼼
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static var squareshapeSplit2x2DottedOutside: SFSymbol { .init(rawValue: "squareshape.split.2x2.dotted.outside") }

    /// 􂺷
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Shapes
    static var starHexagon: SFSymbol { .init(rawValue: "star.hexagon") }

    /// 􂺸
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    /// - Multicolor (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Multicolor
    /// - Shapes
    static var starHexagonFill: SFSymbol { .init(rawValue: "star.hexagon.fill") }

    /// 􂹾
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var suvSideArrowLeftAndRight: SFSymbol { .init(rawValue: "suv.side.arrow.left.and.right") }

    /// 􂹿
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var suvSideArrowLeftAndRightFill: SFSymbol { .init(rawValue: "suv.side.arrow.left.and.right.fill") }

    /// 􂼟
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Automotive
    static var suvSideHillDownAndGaugeOpenWithLinesNeedle25percentAndArrowtriangle: SFSymbol { .init(rawValue: "suv.side.hill.down.and.gauge.open.with.lines.needle.25percent.and.arrowtriangle") }

    /// 􂼠
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Automotive
    static var suvSideHillDownAndGaugeOpenWithLinesNeedle25percentAndArrowtriangleFill: SFSymbol { .init(rawValue: "suv.side.hill.down.and.gauge.open.with.lines.needle.25percent.and.arrowtriangle.fill") }

    /// 􂺫
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var truckPickupSideArrowLeftAndRight: SFSymbol { .init(rawValue: "truck.pickup.side.arrow.left.and.right") }

    /// 􂺬
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Categories:
    /// - Automotive
    static var truckPickupSideArrowLeftAndRightFill: SFSymbol { .init(rawValue: "truck.pickup.side.arrow.left.and.right.fill") }

    /// 􂼣
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Automotive
    static var truckPickupSideHillDownAndGaugeOpenWithLinesNeedle25percentAndArrowtriangle: SFSymbol { .init(rawValue: "truck.pickup.side.hill.down.and.gauge.open.with.lines.needle.25percent.and.arrowtriangle") }

    /// 􂼤
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    ///
    /// Categories:
    /// - Automotive
    static var truckPickupSideHillDownAndGaugeOpenWithLinesNeedle25percentAndArrowtriangleFill: SFSymbol { .init(rawValue: "truck.pickup.side.hill.down.and.gauge.open.with.lines.needle.25percent.and.arrowtriangle.fill") }
}
