// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, visionOS 1.0, *)
extension SFSymbol {
    internal static var categoriesAvailableSince2_2: [SFSymbol : Set<Category>] {
        [
            applewatchSideRight: [.devices],
            characterBubble: [.communication],
            characterBubbleFill: [.communication, .multicolor],
            characterCursorIbeam: [.textformatting],
            characterTextbox: [.textformatting]
        ]
    }
}
