// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, visionOS 1.0, *)
extension SFSymbol {
    internal static var variantsAvailableSince2_2: [SFSymbol : (base: SFSymbol, type: String)] {
        [
            characterBubbleFill: (base: .characterBubble, type: "fill"),
            hifispeakerAndHomepodminiFill: (base: .hifispeakerAndHomepodmini, type: "fill"),
            homepodAndHomepodminiFill: (base: .homepodAndHomepodmini, type: "fill"),
            homepodmini2Fill: (base: .homepodmini2, type: "fill"),
            homepodminiFill: (base: .homepodmini, type: "fill"),
            rectangleTopthirdInsetFill: (base: .rectangleTopthirdInset, type: "fill")
        ]
    }
}
