// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4, visionOS 1.0, *)
extension SFSymbol {
    internal static var keywordsAvailableSince4_2: [SFSymbol : Set<String>] {
        [
            beatsPowerbeatsLeft: ["audio", "sound", "speaker"],
            beatsPowerbeatsRight: ["audio", "sound", "speaker"],
            beatsPowerbeats3Left: ["audio", "sound", "speaker"],
            beatsPowerbeats3Right: ["audio", "sound", "speaker"]
        ]
    }
}
