// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5, visionOS 1.0, *)
extension SFSymbol {
    internal static var variantsAvailableSince3_3: [SFSymbol : (base: SFSymbol, type: String)] {
        [
            cameraMacroCircle: (base: .cameraMacro, type: "circle"),
            cameraMacroCircleFill: (base: .cameraMacroCircle, type: "fill"),
            personBadgeKeyFill: (base: .personBadgeKey, type: "fill")
        ]
    }
}
