// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, visionOS 1.0, *)
extension SFSymbol {
    internal static var categoriesAvailableSince2_1: [SFSymbol : Set<Category>] {
        [
            aqiHigh: [.multicolor, .variable, .weather],
            aqiLow: [.variable, .weather],
            aqiMedium: [.variable, .weather],
            brazilianrealsignCircle: [.commerce, .indices, .variable],
            brazilianrealsignCircleFill: [.commerce, .indices, .multicolor],
            brazilianrealsignSquare: [.commerce, .indices],
            brazilianrealsignSquareFill: [.commerce, .indices, .multicolor],
            cartCircle: [.commerce, .objectsandtools, .variable],
            cartCircleFill: [.commerce, .multicolor, .objectsandtools],
            character: [.textformatting],
            characterBookClosed: [.objectsandtools],
            characterBookClosedFill: [.objectsandtools],
            exclamationmarkApplewatch: [.devices],
            infinityCircle: [.media, .variable],
            infinityCircleFill: [.media, .multicolor],
            ipadBadgePlay: [.devices, .multicolor],
            ipadLandscapeBadgePlay: [.devices, .multicolor],
            iphoneBadgePlay: [.devices, .multicolor],
            iphoneLandscape: [.devices],
            lockApplewatch: [.devices, .privacyandsecurity],
            photoTv: [.devices],
            playTv: [.devices],
            playTvFill: [.devices],
            rectangleBadgePersonCrop: [.human, .multicolor],
            rectangleFillBadgePersonCrop: [.human, .multicolor],
            repeat1Circle: [.arrows, .media, .variable],
            repeat1CircleFill: [.arrows, .media, .multicolor],
            repeatCircle: [.arrows, .media, .variable],
            repeatCircleFill: [.arrows, .media, .multicolor],
            shuffleCircle: [.arrows, .media, .variable],
            shuffleCircleFill: [.arrows, .media, .multicolor],
            textformatSizeLarger: [.accessibility, .textformatting],
            textformatSizeSmaller: [.accessibility, .textformatting],
            tvAndMediabox: [.devices]
        ]
    }
}
