// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 17.6, macOS 14.6, tvOS 17.6, watchOS 10.6, visionOS 1.3, *)
extension SFSymbol {
    internal static var keywordsAvailableSince5_4: [SFSymbol : Set<String>] {
        [
            beatsPill: ["audio", "sound", "speaker"],
            beatsPillFill: ["audio", "sound", "speaker"],
            beatsSolobuds: ["audio", "sound", "speaker"],
            beatsSolobudsChargingcase: ["audio", "sound", "speaker"],
            beatsSolobudsChargingcaseFill: ["audio", "sound", "speaker"],
            beatsSolobudsLeft: ["audio", "sound", "speaker"],
            beatsSolobudsRight: ["audio", "sound", "speaker"]
        ]
    }
}
