// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5, visionOS 2.5, *)
extension SFSymbol {
    internal static var variantsAvailableSince6_4: [SFSymbol : (base: SFSymbol, type: String)] {
        [
            appleIntelligenceBadgeXmark: (base: .appleIntelligence, type: "badge"),
            beatsPowerbeatsPro2ChargingcaseFill: (base: .beatsPowerbeatsPro2Chargingcase, type: "fill")
        ]
    }
}
