// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3, visionOS 1.0, *)
extension SFSymbol {
    internal static var restrictionsAvailableSince3_2: [SFSymbol : Bool] {
        [
            airpodGen3Left: true,
            airpodGen3Right: true,
            airpodsGen3: true,
            airpodsGen3ChargingcaseWireless: true,
            airpodsGen3ChargingcaseWirelessFill: true,
            beatsFitPro: true,
            beatsFitProChargingcase: true,
            beatsFitProChargingcaseFill: true,
            beatsFitProLeft: true,
            beatsFitProRight: true
        ]
    }
}
