// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2, visionOS 1.1, *)
extension SFSymbol {
    internal static var variantsAvailableSince5_2: [SFSymbol : (base: SFSymbol, type: String)] {
        [
            squareAndArrowUpBadgeClock: (base: .squareAndArrowUp, type: "badge"),
            squareAndArrowUpBadgeClockFill: (base: .squareAndArrowUpBadgeClock, type: "fill")
        ]
    }
}
