// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 17.4, macOS 14.4, tvOS 17.4, watchOS 10.4, visionOS 1.1, *)
extension SFSymbol {
    internal static var variantsAvailableSince5_3: [SFSymbol : (base: SFSymbol, type: String)] {
        [
            appleMeditateSquareStackFill: (base: .appleMeditateSquareStack, type: "fill"),
            appleTerminalCircle: (base: .appleTerminal, type: "circle"),
            appleTerminalCircleFill: (base: .appleTerminalCircle, type: "fill"),
            arrowDownAppDashed: (base: .arrowDownApp, type: "dashed"),
            ipadBadgeExclamationmark: (base: .ipad, type: "badge"),
            ipadGen1BadgeExclamationmark: (base: .ipadGen1, type: "badge"),
            ipadGen1LandscapeBadgeExclamationmark: (base: .ipadGen1Landscape, type: "badge"),
            ipadGen2BadgeExclamationmark: (base: .ipadGen2, type: "badge"),
            ipadGen2LandscapeBadgeExclamationmark: (base: .ipadGen2Landscape, type: "badge"),
            ipadLandscapeBadgeExclamationmark: (base: .ipadLandscape, type: "badge"),
            iphoneBadgeExclamationmark: (base: .iphone, type: "badge"),
            iphoneGen1BadgeExclamationmark: (base: .iphoneGen1, type: "badge"),
            iphoneGen2BadgeExclamationmark: (base: .iphoneGen2, type: "badge"),
            iphoneGen3BadgeExclamationmark: (base: .iphoneGen3, type: "badge"),
            medalStarFill: (base: .medalStar, type: "fill"),
            plusCircleDashed: (base: .plusCircle, type: "dashed")
        ]
    }
}
