// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 17.6, macOS 14.6, tvOS 17.6, watchOS 10.6, visionOS 1.3, *)
extension SFSymbol {
    internal static var categoriesAvailableSince5_4: [SFSymbol : Set<Category>] {
        [
            beatsPill: [.devices],
            beatsPillFill: [.devices],
            beatsSolobuds: [.devices],
            beatsSolobudsChargingcase: [.devices],
            beatsSolobudsChargingcaseFill: [.devices],
            beatsSolobudsLeft: [.devices],
            beatsSolobudsRight: [.devices]
        ]
    }
}
