// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5, visionOS 1.0, *)
extension SFSymbol {
    internal static var categoriesAvailableSince3_3: [SFSymbol : Set<Category>] {
        [
            cameraMacro: [.cameraandphotos, .nature],
            cameraMacroCircle: [.cameraandphotos, .nature, .variable],
            cameraMacroCircleFill: [.cameraandphotos, .multicolor, .nature],
            keyViewfinder: [.objectsandtools, .privacyandsecurity],
            personBadgeKey: [.human, .objectsandtools],
            personBadgeKeyFill: [.human, .objectsandtools]
        ]
    }
}
