// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3, visionOS 1.0, *)
extension SFSymbol {
    internal static var keywordsAvailableSince3_2: [SFSymbol : Set<String>] {
        [
            airpodGen3Left: ["audio", "sound", "speaker"],
            airpodGen3Right: ["audio", "sound", "speaker"],
            airpodsGen3: ["audio", "sound", "speaker"],
            airpodsGen3ChargingcaseWireless: ["audio"],
            airpodsGen3ChargingcaseWirelessFill: ["audio"]
        ]
    }
}
