// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1, visionOS 1.0, *)
extension SFSymbol {
    internal static var restrictionsAvailableSince4_1: [SFSymbol : Bool] {
        [
            ipadAndIphoneSlash: true,
            ipadGen1: true,
            ipadGen1BadgePlay: true,
            ipadGen1Landscape: true,
            ipadGen1LandscapeBadgePlay: true,
            ipadGen2: true,
            ipadGen2BadgePlay: true,
            ipadGen2Landscape: true,
            ipadGen2LandscapeBadgePlay: true,
            iphoneGen1: true,
            iphoneGen1BadgePlay: true,
            iphoneGen1Circle: true,
            iphoneGen1CircleFill: true,
            iphoneGen1Landscape: true,
            iphoneGen1RadiowavesLeftAndRight: true,
            iphoneGen1RadiowavesLeftAndRightCircle: true,
            iphoneGen1RadiowavesLeftAndRightCircleFill: true,
            iphoneGen1Slash: true,
            iphoneGen1SlashCircle: true,
            iphoneGen1SlashCircleFill: true,
            iphoneGen2: true,
            iphoneGen2BadgePlay: true,
            iphoneGen2Circle: true,
            iphoneGen2CircleFill: true,
            iphoneGen2Landscape: true,
            iphoneGen2RadiowavesLeftAndRight: true,
            iphoneGen2RadiowavesLeftAndRightCircle: true,
            iphoneGen2RadiowavesLeftAndRightCircleFill: true,
            iphoneGen2Slash: true,
            iphoneGen2SlashCircle: true,
            iphoneGen2SlashCircleFill: true,
            iphoneGen3: true,
            iphoneGen3BadgePlay: true,
            iphoneGen3Circle: true,
            iphoneGen3CircleFill: true,
            iphoneGen3Landscape: true,
            iphoneGen3RadiowavesLeftAndRight: true,
            iphoneGen3RadiowavesLeftAndRightCircle: true,
            iphoneGen3RadiowavesLeftAndRightCircleFill: true,
            iphoneGen3Slash: true,
            iphoneGen3SlashCircle: true,
            iphoneGen3SlashCircleFill: true,
            macbookAndIpad: true,
            macbookAndIphone: true
        ]
    }
}
