// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 13.1, macOS 11.0, tvOS 13.0, watchOS 6.1, visionOS 1.0, *)
extension SFSymbol {
    internal static var variantsAvailableSince1_1: [SFSymbol : (base: SFSymbol, type: String)] {
        [
            arrowUturnLeftCircleBadgeEllipsis: (base: .arrowUturnLeftCircle, type: "badge"),
            aspectratioFill: (base: .aspectratio, type: "fill"),
            circleGrid2x2Fill: (base: .circleGrid2x2, type: "fill"),
            flipHorizontalFill: (base: .flipHorizontal, type: "fill"),
            mappinCircle: (base: .mappin, type: "circle"),
            mappinCircleFill: (base: .mappinCircle, type: "fill"),
            paperclipCircle: (base: .paperclip, type: "circle"),
            paperclipCircleFill: (base: .paperclipCircle, type: "fill"),
            pinCircle: (base: .pin, type: "circle"),
            pinCircleFill: (base: .pinCircle, type: "fill"),
            scissorsBadgeEllipsis: (base: .scissors, type: "badge")
        ]
    }
}
